# Assignment-1: Transformations and representations

Team Name: Robotnix

Roll number: 2018111010 2018113003

# Instructions

- Code must be written in Python in Jupyter Notebooks. We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. See `Set Up` for detailed step-by-step instructions about the installation setup.
- Save all your results in ```results/<question_number>/<sub_topic_number>/```
- The **References** section provides you with important resources to solve the assignment.
- For this assignment, you will be using Open3D extensively. Refer to [Open3D Documentation](http://www.open3d.org/docs/release/): you can use the in-built methods and **unless explicitly mentioned**, don't need to code from scratch for this assignment. 
- Make sure your code is modular since you may need to reuse parts for future assignments.
- Answer the descriptive questions in your own words with context & clarity. Do not copy answers from online resources or lecture notes.
- The **deadline** for this assignment is on 11/09/2021 at 11:55pm. Please note that there will be no extensions.
- Plagiarism is **strictly prohibited**.


# Submission Instructions

1. Make sure your code runs without any errors after reinitializing the kernel and removing all saved variables.
2. After completing your code and saving your results, zip the folder with name as ``Team_<team_name>_MR2021_Assignment_<assignment_number>.zip``

# Set Up

We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. All assignments will be python based, hence familiarising yourself with Python is essential.


## Setting up Anaconda environment (Recommended)

1. Install Anaconda or Miniconda from [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) depending on your requirements.
2. Now simply run `conda env create -f environment.yml` in the current folder to create an environment `mr_assignment1` (`environment.yml` can be found in `misc/`).
3. Activate it using `conda activate mr_assignment1`.

## Setting up Virtual environment using venv

You can also set up a virtual environment using venv

1. Run `sudo apt-get install python3-venv` from command line.
2. `python3 -m venv ~/virtual_env/mr_assignment1`. (you can set the environment path to anything)
3. `source ~/virtual_env/mr_assignment1/bin/activate`
4. `pip3 install -r requirements.txt` from the current folder (`requirements.txt` can be found in `misc/`).

# 1. Getting started with Open3D

Open3D is an open-source library that deals with 3D data, such as point clouds, mesh. We'll be using Open3D frequently as we work with point clouds. Let's start with something simple:

<img src="misc/bunny.jpg" alt="drawing" width="200"/>

1. Read the Stanford Bunny file (in `data/`) given to you and visualise it using Open3D.
2. Convert the mesh to a point cloud and change the colour of points.
3. Set a predefined viewing angle (using Open3D) for visualization and display the axes while plotting.
4. Scale, Transform, and Rotate the rabbit (visualise after each step).
5. Save the point cloud as bunny.pcd.

#### Part 1 (Read bunny data and visualize mesh)

In [2]:
import open3d as o3d
import numpy as np

mesh = o3d.io.read_triangle_mesh("./data/bunny.ply")
o3d.visualization.draw_geometries([mesh])

#### Part 2 (Display as colored point cloud)

In [3]:
pcd = o3d.io.read_point_cloud("./data/bunny.ply")
pcd.paint_uniform_color([1, 0.7, 0])
o3d.visualization.draw_geometries([pcd])

#### Part 3 (View from predefined angle with axes)

In [4]:
print(np.asarray(pcd.points))

[[-0.0378297   0.12794     0.00447467]
 [-0.0447794   0.128887    0.00190497]
 [-0.0680095   0.151244    0.0371953 ]
 ...
 [-0.0704544   0.150585   -0.0434585 ]
 [-0.0310262   0.153728   -0.00354608]
 [-0.0400442   0.15362    -0.00816685]]


In [5]:
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1)
o3d.visualization.draw_geometries([pcd, coord],
                                  zoom=1.5,
                                  front=[2, 2, 2],
                                  lookat=[0, 0, 0],
                                  up=[0, 1, 0])

#### Part 4 (Scale, Translate, Rotate)

In [6]:
def get_rot_mat(alpha, beta, gamma):
    Rx = np.zeros((3,3))
    Rx[0,0] = 1
    Rx[1,1] = np.cos(alpha)
    Rx[1,2] = -np.sin(alpha)
    Rx[2,1] = np.sin(alpha)
    Rx[2,2] = np.cos(alpha)
    
    Ry = np.zeros((3,3))
    Ry[1,1] = 1
    Ry[0,0] = np.cos(beta)
    Ry[0,2] = -np.sin(beta)
    Ry[2,0] = np.sin(beta)
    Ry[2,2] = np.cos(beta)
    
    Rz = np.zeros((3,3))
    Rz[2,2] = 1
    Rz[0,0] = np.cos(gamma)
    Rz[0,1] = -np.sin(gamma)
    Rz[1,0] = np.sin(gamma)
    Rz[1,1] = np.cos(gamma)
    
    # X-Y-Z format
#     print(Rx, Ry, Rz)
    rotation_matrix = np.dot(Rx, np.dot(Ry, Rz))
    return rotation_matrix

In [8]:
# Initial

pcd = o3d.io.read_point_cloud("./data/bunny.ply")
pcd.paint_uniform_color([1, 0.7, 0])
o3d.visualization.draw_geometries([pcd, coord],
                                  zoom=1.5,
                                  front=[2, 2, 2],
                                  lookat=[0, 0, 0],
                                  up=[0, 1, 0])

# Scale

scale_factor = 3
pcd = pcd.scale(scale_factor, center=[0.0,0.0,0.0])
o3d.visualization.draw_geometries([pcd, coord],
                                  zoom=1.5,
                                  front=[2, 2, 2],
                                  lookat=[0, 0, 0],
                                  up=[0, 1, 0])

# Rotate

rotation_mat = get_rot_mat(0, np.pi/2, 0)
pcd = pcd.rotate(rotation_mat)
o3d.visualization.draw_geometries([pcd, coord],
                                  zoom=1.5,
                                  front=[2, 2, 2],
                                  lookat=[0, 0, 0],
                                  up=[0, 1, 0])

# Translate

translation_vector = [0, 0, 2]
pcd = pcd.translate(translation_vector)
o3d.visualization.draw_geometries([pcd, coord],
                                  zoom=1.5,
                                  front=[2, 2, 2],
                                  lookat=[0, 0, 0],
                                  up=[0, 1, 0])

(See the coordinate frame for reference for transformations)

#### Part 4 (Save Point Cloud)

In [9]:
o3d.io.write_point_cloud('./data/bunny.pcd',pcd)

True

# 2. Transformations and representations

## a) Euler angles
1. Write a function that returns a rotation matrix given the angles $\alpha$, $\beta$, and $\gamma$ in radians (X-Y-Z)

2. Solve for angles using ```fsolve from scipy``` for three initializations of your choice and compare.
$$M(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0.26200263 & -0.19674724 & 0.944799 \\0.21984631 & 0.96542533 & 0.14007684 \\
    -0.93969262 & 0.17101007 & 0.29619813\end{array}\right] 
$$

$$N(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0 & -0.173648178 &  0.984807753 \\0 & 0.984807753 & 0.173648178 \\
    -1 & 0 & 0\end{array}\right] 
$$

3. What is a Gimbal lock? 

4. Show an example where a Gimbal lock occurs and visualize the Gimbal lock on the given bunny point cloud. You have to show the above by **animation** (cube rotating along each axis one by one).
    - *Hint: Use Open3D's non-blocking visualization and discretize the rotation to simulate the animation. For example, if you want to rotate by $30^{\circ}$ around a particular axis, do in increments of $5^{\circ}$ 6 times to make it look like an animation.*


#### Part 1 (Get rotation mat)

In [10]:
import numpy as np

# Part 1

def get_rot_mat(alpha, beta, gamma):
    Rx = np.zeros((3,3))
    Rx[0,0] = 1
    Rx[1,1] = np.cos(alpha)
    Rx[1,2] = -np.sin(alpha)
    Rx[2,1] = np.sin(alpha)
    Rx[2,2] = np.cos(alpha)
    
    Ry = np.zeros((3,3))
    Ry[1,1] = 1
    Ry[0,0] = np.cos(beta)
    Ry[0,2] = -np.sin(beta)
    Ry[2,0] = np.sin(beta)
    Ry[2,2] = np.cos(beta)
    
    Rz = np.zeros((3,3))
    Rz[2,2] = 1
    Rz[0,0] = np.cos(gamma)
    Rz[0,1] = -np.sin(gamma)
    Rz[1,0] = np.sin(gamma)
    Rz[1,1] = np.cos(gamma)
    
    # X-Y-Z format
#     print(Rx, Ry, Rz)
    rotation_matrix = np.dot(Rx, np.dot(Ry, Rz))
    return rotation_matrix

In [11]:
print(get_rot_mat(0, 0, np.pi))

[[-1.0000000e+00 -1.2246468e-16  0.0000000e+00]
 [ 1.2246468e-16 -1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]


#### Part 2 (solving for angles)

In [12]:
import scipy

In [13]:
from scipy.optimize import fsolve

# Part 2

def func1(x):
    mat = get_rot_mat(x[0], x[1], x[2])
    M = [[0.26200263, -0.19674724, 0.944799],
        [0.21984631, 0.96542533, 0.14007684],
        [-0.93969262, 0.17101007, 0.29619813]]
    M = np.array(M)
    return (mat-M).ravel()
    
def func2(x):
    mat = get_rot_mat(x[0], x[1], x[2])
    N = [[0, -0.173648178, 0.984807753],
        [0, 0.984807753, 0.173648178],
        [-1, 0, 0]]
    N = np.array(N)
    return (mat-N).ravel()
    
initializations = [np.zeros((9)), np.ones((9)), np.full((9), np.pi)]
print("Three answers for M")
for initialization in initializations:
    root = fsolve(func1, initialization)
    print(root[:3])  # Only first three are useful variables, rest are dummy variables
print("Three answers for N")
for initialization in initializations:
    root = fsolve(func2, initialization)
    print(root[:3])  # Only first three are useful variables, rest are dummy variables
    
print("As we can see, we get same values of angles as solution if we solve using 0 or 1 as initail angles but we get a different answer with pi as initial angles")

Three answers for M
[-0.44174662 -1.23698059  0.64409996]
[-0.44174662 -1.23698059  0.64409996]
[2.69984603 4.37857325 3.78569262]
Three answers for N
[-1.57079633 -1.3962634   1.57079633]
[-1.57369192 -1.3972677   1.57369192]
[1.57079633 4.53785605 4.71238898]
As we can see, we get same values of angles as solution if we solve using 0 or 1 as initail angles but we get a different answer with pi as initial angles


/home/arpan/miniconda3/envs/mr_assignment1/lib/python3.8/site-packages/scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


#### Part 3 (What is a gimbal lock?)

Gimbal lock is when a rotating body operating in euler rotation angles loses a degree of freedom when one of the axes (the middle one) rotates too far. For example, in XYZ system, if Y rotates by 90 degrees then the X and Z rotations are aligned and one of them becomes redundant. The other angle becomes unavailable for rotation and hence the rotations are restrained.

#### Part 4 (Gimbal Lock Animation)

In [14]:
import open3d as o3d
import numpy as np

In [15]:
import time
speed = np.radians(5) # degrees

def get_angle(obj, curr, required):
    required = np.array(required)
    curr = np.array(curr)
    r1 = obj.get_rotation_matrix_from_zyx(curr)
    r2 = obj.get_rotation_matrix_from_zyx(curr + required)
    r3 = np.matmul(r2, r1.transpose())
    return r3

def run(obj, bunny, vis, center, curr, required):
    required = np.radians(np.array(required))
    curr = np.radians(np.array(curr)) 

    step = speed
    if required[0] < 0:
        step = -step
    r = get_angle(obj, curr, (step, 0, 0))
    for _ in range(int(abs(required[0])/speed)):
        obj.rotate(r, center=center)
        bunny.rotate(r, center=center)
        vis.update_geometry(obj)
        vis.update_geometry(bunny)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.15)
    curr[0] += required[0]
    step = speed
    if required[1] < 0:
        step = -step
    r = get_angle(obj, curr, (0, step, 0))
    for _ in range(int(abs(required[1])/speed)):
        obj.rotate(r, center=center)
        bunny.rotate(r, center=center)
        vis.update_geometry(obj)
        vis.update_geometry(bunny)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.15)
    curr[1] += required[1]
    step = speed
    if required[2] < 0:
        step = -step
    r = get_angle(obj, curr, (0, 0, step))
    for _ in range(int(abs(required[2])/speed)):
        obj.rotate(r, center=center)
        bunny.rotate(r, center=center)
        vis.update_geometry(obj)
        vis.update_geometry(bunny)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.15)
    curr[2] += required[2]

In [16]:
def gimbal(angle):

#     shpere_obj = o3d.geometry.TriangleMesh.create_sphere(radius=0.03)
#     shpere_obj.paint_uniform_color([0, 1, 1])
#     shpere_obj.translate((0.75, 0.75, 0.75))

    bunny = o3d.io.read_point_cloud("./data/bunny.ply")
    bunny = bunny.translate([0.01,-0.07,-0.01])
    bunny = bunny.scale(3, [0,0,0])
    bunny.paint_uniform_color([1, 0.7, 0])

    self_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1)
    world_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1)

    win = o3d.visualization.Visualizer()
    win.create_window()
    win.add_geometry(world_frame)
    win.add_geometry(self_frame)
    win.add_geometry(bunny)
    win.poll_events()
    win.update_renderer()

    time.sleep(1)
    run(self_frame, bunny, win, (0, 0, 0), (0, 0, 0), angle)

    time.sleep(1)
    win.destroy_window()

gimbal((-35, 90, 360))

As we can see, the 90 degree rotation about the green axis, aligns the red and blue axes. Thus, the coordinate frame is never able to rotate about the original red axis in the last rotation. This is the gimbal lock problem. 

## b) Quaternions

1. What makes Quaternions popular in graphics? 
2. Convert a rotation matrix to quaternion and vice versa. Do not use inbuilt libraries for this question.
3. Perform matrix multiplication of two $\mathcal{R}_{3 \times 3}$ rotation matrices and perform the same transformation in the quaternion space. Verify if the final transformation obtained in both the cases are the same.
4. Try to interpolate any 3D model (cube / bunny / not sphere obviously!!) between two rotation matrices and visualize!

The above questions require you to **code your own functions** and **only verify** using inbuilt functions.

#### Part 1 (Why are quaternions poular?)

Quaternions solve a lot of the problems which are faced by euler angles for representing rotations. Quaternions are not susceptible to the problem of Gimbal Lock. Furthermore, quaternions make interpolation from one angle to another much smoother as compared to euler angles where the rotations may need to be out of plane. This is the reason quaternions are very popular alternatives for Euler angles in graphics.

#### Part 2 (Rotation Matrix to Quaternions and vice versa)

In [17]:
def quaternion_to_mat(quat):
    mat = np.zeros((3,3))
    x = quat[0]
    y = quat[1]
    z = quat[2]
    w = quat[3]
    mat[0,0] = 1-2*y*y-2*z*z
    mat[1,1] = 1-2*x*x-2*z*z
    mat[2,2] = 1-2*y*y-2*x*x
    mat[0,1] = 2*(x*y+z*w)
    mat[0,2] = 2*(x*z-y*w)
    mat[1,0] = 2*(x*y-z*w)
    mat[1,2] = 2*(y*z+x*w)
    mat[2,0] = 2*(x*z+y*w)
    mat[2,1] = 2*(y*z-x*w)
    return mat

def mat_to_quaternion(m):
    if (m[2,2] < 0):
        if (m[0,0] > m[1,1]):
            t = 1 + m[0,0] - m[1,1] - m[2,2]
            q = np.array([t, m[0,1]+m[1,0], m[2,0]+m[0,2], m[1,2]-m[2,1]])
        else:
            t = 1 - m[0,0] + m[1,1] - m[2,2]
            q = np.array([m[0,1]+m[1,0], t, m[1,2]+m[2,1], m[2,0]-m[0,2]])
    else:
        if (m[0,0] < -m[1,1]):
            t = 1 - m[0,0] - m[1,1] + m[2,2]
            q = np.array([m[2,0]+m[0,2], m[1,2]+m[2,1], t, m[0,1]-m[1,0]])
        else:
            t = 1 + m[0,0] + m[1,1] + m[2,2]
            q = np.array([m[1,2]-m[2,1], m[2,0]-m[0,2], m[0,1]-m[1,0], t])
    q *= 0.5 / (t**(0.5));
    return q

In [18]:
quat = np.array([2**(-0.5), 0, 0, 2**(-0.5)])
print(quat)
mat = quaternion_to_mat(quat)
print(mat)
q2 = mat_to_quaternion(mat)
print(q2)

[0.70710678 0.         0.         0.70710678]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00 -2.22044605e-16]]
[0.70710678 0.         0.         0.70710678]


We can see that the quaternion is obtained back from the initial quaternion after conversion to rotation matrix and back

#### Part 3 (Muliplication in quaternion and rot matrix space)

In [19]:
rot_matrices = [get_rot_mat(0, 0, np.pi), get_rot_mat(np.pi/2, np.pi/2, 0)]

def mult_quaternions(q1, q2):
    b, c, d, a = q1.tolist()
    f, g, h, e = q2.tolist()
    return np.array([a*f+b*e+c*h-d*g, a*g-b*h+c*e+d*f, a*h+b*g-c*f+d*e, a*e-b*f-c*g-d*h])

new_rot_mat = np.dot(rot_matrices[1], rot_matrices[0])
quats = [mat_to_quaternion(rot_matrices[0]), mat_to_quaternion(rot_matrices[1])]

new_quaternion_1 = mult_quaternions(quats[0], quats[1])
new_quaternion_2 = mult_quaternions(quats[1], quats[0])

print("Two quaternions: ", new_quaternion_1, new_quaternion_2)
print("Quaternion of multiplied rotation matrices: ", mat_to_quaternion(new_rot_mat))

Two quaternions:  [-0.5 -0.5  0.5 -0.5] [ 0.5  0.5  0.5 -0.5]
Quaternion of multiplied rotation matrices:  [ 0.5  0.5 -0.5  0.5]


As we can see, the final quaternions produced by the two methods of multiplication are the same (barring the sign, as q and -q produce the same rotation) for one of the two quaternions produced. The reason for 2 possible quaternions is that we can rotate in two ways (clockwise and anti-clockwise).

In [20]:
# Verification using scipy 

from scipy.spatial.transform import Rotation as R
r1 = R.from_matrix(rot_matrices[0])
r2 = R.from_matrix(rot_matrices[1])
print((r2*r1).as_matrix())
print(new_rot_mat)

print(quats[0], quats[1])
print(r1.as_quat(), r2.as_quat())

print((r2*r1).as_quat())
print((r1*r2).as_quat())
print(mat_to_quaternion(new_rot_mat))
print(mult_quaternions(quats[0], quats[1]))

[[-1.66533454e-16 -1.66533454e-16 -1.00000000e+00]
 [ 1.00000000e+00 -5.55111512e-17 -1.66533454e-16]
 [ 0.00000000e+00 -1.00000000e+00  1.66533454e-16]]
[[-6.12323400e-17 -7.49879891e-33 -1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17 -6.12323400e-17]
 [ 6.12323400e-17 -1.00000000e+00  3.74939946e-33]]
[ 0.000000e+00  0.000000e+00  1.000000e+00 -6.123234e-17] [-0.5  0.5  0.5  0.5]
[0.000000e+00 0.000000e+00 1.000000e+00 6.123234e-17] [ 0.5 -0.5 -0.5  0.5]
[-0.5 -0.5  0.5  0.5]
[0.5 0.5 0.5 0.5]
[ 0.5  0.5 -0.5  0.5]
[-0.5 -0.5  0.5 -0.5]


#### Part 4 (Quaternion Interpolation [Slerp])

In [1]:
import open3d as o3d
import numpy as np
import time

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [22]:
from copy import deepcopy

def get_rot_mat(alpha, beta, gamma):
    Rx = np.zeros((3,3))
    Rx[0,0] = 1
    Rx[1,1] = np.cos(alpha)
    Rx[1,2] = -np.sin(alpha)
    Rx[2,1] = np.sin(alpha)
    Rx[2,2] = np.cos(alpha)
    
    Ry = np.zeros((3,3))
    Ry[1,1] = 1
    Ry[0,0] = np.cos(beta)
    Ry[0,2] = -np.sin(beta)
    Ry[2,0] = np.sin(beta)
    Ry[2,2] = np.cos(beta)
    
    Rz = np.zeros((3,3))
    Rz[2,2] = 1
    Rz[0,0] = np.cos(gamma)
    Rz[0,1] = -np.sin(gamma)
    Rz[1,0] = np.sin(gamma)
    Rz[1,1] = np.cos(gamma)
    
    rotation_matrix = np.dot(Rx, np.dot(Ry, Rz))
    return rotation_matrix

def quaternion_to_mat(quat):
    mat = np.zeros((3,3))
    x = quat[0]
    y = quat[1]
    z = quat[2]
    w = quat[3]
    mat[0,0] = 1-2*y*y-2*z*z
    mat[1,1] = 1-2*x*x-2*z*z
    mat[2,2] = 1-2*y*y-2*x*x
    mat[0,1] = 2*(x*y+z*w)
    mat[0,2] = 2*(x*z-y*w)
    mat[1,0] = 2*(x*y-z*w)
    mat[1,2] = 2*(y*z+x*w)
    mat[2,0] = 2*(x*z+y*w)
    mat[2,1] = 2*(y*z-x*w)
    return mat

def mat_to_quaternion(m):
    if (m[2,2] < 0):
        if (m[0,0] > m[1,1]):
            t = 1 + m[0,0] - m[1,1] - m[2,2]
            q = np.array([t, m[0,1]+m[1,0], m[2,0]+m[0,2], m[1,2]-m[2,1]])
        else:
            t = 1 - m[0,0] + m[1,1] - m[2,2]
            q = np.array([m[0,1]+m[1,0], t, m[1,2]+m[2,1], m[2,0]-m[0,2]])
    else:
        if (m[0,0] < -m[1,1]):
            t = 1 - m[0,0] - m[1,1] + m[2,2]
            q = np.array([m[2,0]+m[0,2], m[1,2]+m[2,1], t, m[0,1]-m[1,0]])
        else:
            t = 1 + m[0,0] + m[1,1] + m[2,2]
            q = np.array([m[1,2]-m[2,1], m[2,0]-m[0,2], m[0,1]-m[1,0], t])
    q *= 0.5 / (t**(0.5));
    return q
    
def run(bunny, vis, center, mat1, mat2):
    intervals = np.arange(0,1.001,0.05)
    quat1 = mat_to_quaternion(mat1)
    quat2 = mat_to_quaternion(mat2)
    omega = np.arccos(np.dot(quat1, quat2))
    prev = mat1.T
    for val in intervals:
        intermediate_quat = (np.sin((1-val)*omega)*quat1+np.sin(val*omega)*quat2)/np.sin(omega)
        intermediate_mat = quaternion_to_mat(intermediate_quat)
        bunny.rotate(prev, center=center)
        bunny.rotate(intermediate_mat, center=center)
        prev = intermediate_mat.T
        vis.update_geometry(bunny)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.15)

In [23]:
def interpolate(mat1, mat2):

    bunny = o3d.io.read_point_cloud("./data/bunny.ply")
    bunny = bunny.translate([0.01,-0.07,-0.01])
    bunny = bunny.scale(3, [0,0,0])
    bunny = bunny.rotate(mat1, center=[0,0,0])

    self_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1)
    bunny = self_frame
    world_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1)

    win = o3d.visualization.Visualizer()
    win.create_window()
    win.add_geometry(world_frame)
    win.add_geometry(self_frame)
    win.add_geometry(bunny)
    win.poll_events()
    win.update_renderer()

    time.sleep(1)
    run(bunny, win, (0, 0, 0), mat1, mat2)

    time.sleep(1)
    win.destroy_window()

interpolate(get_rot_mat(0, 0, 0), get_rot_mat(-np.pi/4, np.pi/2, np.pi/2))

As we can see, the rotation happens smoothly due to quaternion intepolation.

## c) Exponential maps (Bonus)

1. What is the idea behind exponential map representation of rotation matrices?
2. Perform matrix exponentiation and obtain the rotation matrix to rotate a vector $P$ around $\omega$ for $\theta$ seconds.
$$
\omega = \begin{bmatrix}2 \\ 1 \\ 15 \end{bmatrix}
$$

$$
\theta = 4.1364
$$

3. Compute the logarithmic map (SO(3) to so(3)) of the rotation matrix to obtain the rotation vector and the angle of rotation
$$
\begin{bmatrix}
0.1 &  -0.9487 & 0.3 \\
0.9487 & 0.  & -0.3162 \\
0.3   &  0.3162  & 0.9 
\end{bmatrix}
$$
You can use inbuilt libraries **only to verify** your results.

#### Part 1 (What is the idea behind exponential map representation of rotation matrices?)

The idea behind exponential maps is to change the coordinate system from cartesian to polar coordinates. This conversion is useful as some applications prefer polar coordiantes due to its geometric meaning.

#### Part 2 (Exponential Map to rotate around $\omega$ for $\theta$ seconds)

In [15]:
def exp_map(w,t):
    ''' 
    Rodrigues formula is used for approximation of exponential map.
    i.e. exp(wt) = I + [w]sin(t) + [w]^2(1 - cos(t))
    
    Note : [w] is a nxm matrix as follows : w x p (cross product) = [w]p
    Hence, [w] = [[0,-w3,w2],[w3,0,-w1],[-w2,w1,0]] 
    '''

    # The unit vector corresponding to rotation vector is required
    w = w/np.linalg.norm(w)
    w_matrix = np.array([[0,-w[2],w[1]],[w[2],0,-w[0]],[-w[1],w[0],0]])
    
    # Generating the Identity Matrix
    iden = np.zeros(shape=(3,3))
    for i in range(3):
        iden[i][i] = 1
    
    res = iden + w_matrix*np.sin(t) + np.matmul(w_matrix,w_matrix)*(1 - np.cos(t))
    return res

In [52]:
R = exp_map(w = [2,1,15],t = 4.1364)
print('The rotation matrix is :')
print(R)

The rotation matrix is :
[[-0.51780074  0.84292002  0.14617876]
 [-0.81605629 -0.53794854  0.21133741]
 [ 0.25677718 -0.00985943  0.96642034]]


##### Verification

In [58]:
from scipy.spatial.transform import Rotation as R
w = np.array([2,1,15])
w = w/np.linalg.norm(w)
t = 4.1364
r = R.from_rotvec(t*w)
r.as_matrix()

array([[-0.51780074,  0.84292002,  0.14617876],
       [-0.81605629, -0.53794854,  0.21133741],
       [ 0.25677718, -0.00985943,  0.96642034]])

Thus, the matrix generated is verified to be the same as the result from the inbuilt library

#### Part 3 (SO(3) $\rightarrow$ so(3))

In [63]:
def get_wt(R):
    R = np.asarray(R)
    iden = np.zeros(shape=(3,3))
    for i in range(3):
        iden[i][i] = 1

    # If R == I, then the angle of rotation is 0 and the rotation vector is not defined
    compare_identity = R == iden
    if compare_identity.all():
        return [0,np.inf]

    # If trace(R) == -1, then there is a degeneracy of three in the rotation vector, of which one is chosen
    # The angle of rotation is pi 
    elif np.trace(R) == -1:
        t = np.pi
        w = (1/np.sqrt(2*(1+R[2][2])))*[R[0][2],R[1][2],1 + R[2][2]]

        return [w,t]

    else:
        t = np.arccos(0.5*(np.trace(R) - 1))
        w = (1/(2*np.sin(t)))*np.array([R[2][1] - R[1][2],R[0][2] - R[2][0],R[1][0] - R[0][1]])

        return [w,t]

In [61]:
R = np.array([[0.1,-0.9487,0.3],[0.9487,0.0,-0.3162],[0.3,0.3162,0.9]])
w,t = get_wt(R)
print("The unit rotation vector is : ",w)
print("The angle of rotation is : ",t)
print("The combined rotation vector (used for verification) is : ",w*t)

The unit rotation vector is :  [0.3162 0.     0.9487]
The angle of rotation is :  1.5707963267948966
The combined rotation vector (used for verification) is :  [0.4966858  0.         1.49021448]


##### Verification

In [62]:
from scipy.spatial.transform import Rotation as F
R = np.array([[0.1,-0.9487,0.3],[0.9487,0.0,-0.3162],[0.3,0.3162,0.9]])
r = F.from_matrix(R)
print("The rotation vector is :",r.as_rotvec())

The rotation vector is : [0.49668452 0.         1.49021065]


Thus, the matrix generated is verified to be the same as the result from the inbuilt library

# 3. Data representations

## a) Octomaps

1. Why is an Octomap memory efficient?
2. When do we update an Octomap and why?
3. When would you likely use an octomap instead of a point cloud?
 

#### Part 1 (Why is an octomap memory efficient)

Octomaps use two techniques to compress its memory footprint as compared to other solutions. One is clamping and other is pruning. Clamping is an update policy rule which limits the amount of updates required to declare a node free or occupied, with the limit defined by two free variables $l_{min}$ and $l_{max}$. Using this update rule, a bound on the confidence on the mapping can be availed. Due to this, neighbouring voxels can be pruned in order to reduce the total amount of voxels. This results in reduction of redundant information and thus octomap being memory efficient.

There are other benifits which come from using octotrees as their data structure that the resolution of the space can be as coarse or fine as per the requirement. This means that one can safely make the octotree coarse and then add new nodes to it only if conflicting information is obtained. This saves a lot of space as the volume of indivdual volexs can differ greatly depending on whether they are on surface or not thus saving a lot of space.

#### Part 2 (When do we update an Octomap and why?)

An octomap is updated when it gets contradicting infromation from future measurements. The update step changes the state of a voxel if it is contradicting, and it it still contradicts, then it gets children node till no contradiction information is recieved

#### Part 3 (When would you likely use an octomap instead of a point cloud)

A point cloud representation does not map free space or unknown areas nor does it take into account sensor noise and dynamic object information directly. It also is not memory efficient. These are areas where octomaps excels at. Thus in scenarios where the amount of memory is limited, the mapping of unknown and free spaces is important, and also cases where the location has mobile objects, an octomap is more likely to be used than a point cloud representation.

## b) Signed Distance Functions

1. How do we determine object surfaces using SDF?
2. How do we aggregate views from multiple cameras? (just a general overview is fine)
3. Which preserves details better? Voxels or SDF? Why?
4. What’s an advantage of SDF over a point cloud?


#### Part 1 (How do we determine object surfaces using SDF?)

Signed Distance Function (SDF) gives a distance metric for each voxel, the metric signifying the distance between the voxel and the surface. The negative signed distance signifying that the voxel is outside of the bound object and the positive distance signifying that the voxel is inside the bound surface. Thus the surface is the one, where the signed distance is zero. Hence, the object surface is determined where the SDF of the voxel returns zero.

#### Part 2 (How do we aggregate views from multiple cameras?)

A single camera measures the distance and gives a reading D, which is the distance between the voxels and the surface. For multiple cameras, aggregation is done by taking a weighted average of all the distance taken by the cameras. 

For each camera, the update rule as given below is applied to every voxel which intersects the ray between the camera and the surface, thus giving an aggregate distance using information from all the cameras. 

The update rule : <br>
$D \leftarrow \frac{WD + wd}{W + w}$ <br>
$W \leftarrow W + w$

In this, D is the aggregated distance, W is the aggregated weight, with d and w being distance and weight of that particular camera observation.

#### Part 3 (Which preserves details better? Voxels or SDF? Why?)

> Note : An assumption is taken that the comparision is between occupancy map and SDF rather than voxel as voxel is not a surface mapping algorithm to be compared but rather a notation for 3d point

Occupancy maps stores the information of whether a particular voxel is occupied or if it free. SDF on the other hand gives a distance metric between the voxel and the surface, thus there is more information stored in an SDF compared to occupancy map. The distance metric helps in interpolation and thus gives a more precise information on the location of the surface. Thus SDF preserves details better then occupancy maps.

#### Part 4 (What’s an advantage of SDF over a point cloud?)

An advantage that SDF has over point cloud is that maps both free space and occupied space as compared to point clouds which only map occupied space. Another advantage is that it takes constant memory for mapping which would be useful in densely occupied maps, where the amount of information required by point clouds would be too much as it takes three values per voxel as compared to SDF which only requires one. Thus in densely occupied regions (In regions where O(total_voxels) $\approx$ O(occupied_voxels)), memory required required to store point clouds would be almost three times the memory required to store SDFs.

# References and Resources

1. Gimbal locks and quaternions: https://youtu.be/YF5ZUlKxSgE
2. Exponential map: 
    1. 3 Blue 1 Brown: https://youtu.be/O85OWBJ2ayo
    2. Northwestern Robotics: https://youtu.be/v_KBHaG0mas
3. Bunny ply is taken from: http://graphics.im.ntu.edu.tw/~robin/courses/cg03/model/